### ISSUE TITLE
If people mention their GitHub profile, suggest connection

### ISSUE THREAD

**Issue by honzajavorek** [juniorguru/chick#18]
- Example: https://discord.com/channels/769966886598737931/788823881024405544/1123942120621883432
- What should be suggested: https://support.discord.com/hc/en-us/articles/10388356626711-Connections-Linked-Roles-Admins
- Why: one day I might automatically add people with linked GitHub to my GitHub org or they could have other perks

**Comment by honzajavorek** [comment]
I figured out the GitHub connection could be actually an enabler for a whole new amazing product, so having people connected like this would be very desired in the future.

**Comment by dariagrudzien** [comment]
I'm ready to dig into this, but I'm blocked because I can't generate the API keys. https://bots.ondiscord.xyz/me/keys just hangs for me, no matter the device, network, browser. I'm trying to get help on the Bots discord server.

**Comment by honzajavorek** [comment]
I’m AFK, but the URL looks shady 😀

**Comment by honzajavorek** [comment]
@dariagrudzien Does this tutorial work for you?

1. https://docs.pycord.dev/en/master/discord.html
2. https://docs.pycord.dev/en/master/quickstart.html

**Comment by dariagrudzien** [comment]
@honzajavorek Success! Thank you!

**Comment by dariagrudzien** [comment]
@honzajavorek A sanity check to make sure that I fully understand the task here:
- When user includes a link to GH
- suggest in a thread/DM (?) message 
- that they open Discord settings, navigate to Connections and connect their GH? [I checked the browser client, and I can't find a direct link to Connections]

Is this correct? Is there more to it? What should the message say exactly?

**Comment by honzajavorek** [comment]
@dariagrudzien That seems correct. The suggestion should be part of the intro message in the intro thread: https://github.com/juniorguru/juniorguru-chick/blob/3425aa1bec1401700f7315d3dde8c161c7853ecc/juniorguru_chick/lib/intro.py#L61

**Comment by honzajavorek** [comment]
And you're correct that unfortunately, it seems that the `https://discord.com/channels/@me` part of Discord doesn't support deep linking to specific sections.

**Comment by honzajavorek** [comment]
I think this is implemented now! 🎉
